--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sanjarbek/Pictures/wallpapers/Dynamic-Wallpapers/Dark/highway_dark.jpg"

-- Special
background="#020203"
foreground="#bbd0e3"
cursor="#bbd0e3"

-- Colors
color0="#020203"
color1="#44527A"
color2="#4A5A87"
color3="#546796"
color4="#5A71A3"
color5="#6176A5"
color6="#739EC3"
color7="#bbd0e3"
color8="#82919e"
color9="#44527A"
color10="#4A5A87"
color11="#546796"
color12="#5A71A3"
color13="#6176A5"
color14="#739EC3"
color15="#bbd0e3"
